title: tanob's blog
permalink: date
highlighter: pygments
url: http://blog.tanob.me
disqus_short_name: tanob-github
feed_url: http://feeds.feedburner.com/tanob-blog

author:
  name: Adriano Bonat
  email: adrianob@gmail.com

